stages:
  - build
  - test
  - doc

build:
  stage: build
  image: rust:1.83-bullseye
  before_script:
    - apt update -y
    - apt install cmake clang -y
  script: 
    - cargo build --no-default-features

rustdoc:
  stage: doc
  dependencies: [build]
  image: rust:1.83-bullseye
  before_script:
    - apt update -y
    - apt install cmake clang -y
  script: 
    - cargo doc --no-default-features

test:
  stage: test
  dependencies: [build]
  image: rust:1.83-bullseye
  before_script:
    - apt update -y
    - apt install cmake clang -y
  script:
    - cargo test --no-default-features
