stages:
  - build
  - test
  - doc

build:
  stage: build
  image: rust:1.83-bullseye
  before_script:
    - apt update
    - apt install cmake
  script: 
    - cargo build --no-default-features
  artifacts:
    paths:
      - target

rustdoc:
  stage: doc
  dependencies: [build]
  image: rust:1.83-bullseye
  script: 
    - cargo doc --no-default-features

test:
  stage: test
  dependencies: [build]
  image: rust:1.83-bullseye
  script:
    - cargo test --no-default-features
